/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AAPackage;

/**
 *
 * @author Collins
 */
public class PaymentRecord extends javax.swing.JFrame {

    /**
     * Creates new form PaymentRecord
     */
    public PaymentRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentRecord = new javax.swing.JPanel();
        javax.swing.JLabel tenantsName12 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName14 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName15 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName16 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName17 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName18 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName19 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName20 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName21 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName22 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName25 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName26 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName27 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName28 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName29 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName30 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName31 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName32 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName33 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName34 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName35 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName36 = new javax.swing.JLabel();
        javax.swing.JLabel tenantsName37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tenantsName12.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName12.setText("HOUSE");

        tenantsName14.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName14.setText("DATE PAID");

        tenantsName15.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName15.setText("AMOUNT TO BE PAID");

        tenantsName16.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName16.setText("AMOUNT PAID");

        tenantsName17.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName17.setText("AMOUNT PAID");

        tenantsName18.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName18.setText("AMOUNT PAID");

        tenantsName19.setFont(new java.awt.Font("Open Sans Medium", 1, 15)); // NOI18N
        tenantsName19.setText("PAYMENT HISTORY");

        tenantsName20.setFont(new java.awt.Font("Open Sans Medium", 1, 15)); // NOI18N
        tenantsName20.setText("Tenant Name");

        tenantsName21.setFont(new java.awt.Font("Open Sans Medium", 1, 15)); // NOI18N
        tenantsName21.setText("House Class");

        tenantsName22.setFont(new java.awt.Font("Open Sans Medium", 1, 15)); // NOI18N
        tenantsName22.setText("House Allocated");

        tenantsName25.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName25.setText("LANDLORD");

        tenantsName26.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName26.setText("NAME");

        tenantsName27.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName27.setText("NAME");

        tenantsName28.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName28.setText("AGENT INCHARGE");

        tenantsName29.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName29.setText("HOUSE CLASS");

        tenantsName30.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName30.setText("AMOUNT PAID");

        tenantsName31.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName31.setText("AMOUNT COLLECTED");

        tenantsName32.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName32.setText("AMOUNT PAID");

        tenantsName33.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName33.setText("AMOUNT DUE");

        tenantsName34.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName34.setText("AMOUNT PAID");

        tenantsName35.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName35.setText("AMOUNT PAID");

        tenantsName36.setFont(new java.awt.Font("Open Sans Medium", 2, 15)); // NOI18N
        tenantsName36.setText("AMOUNT COLLECTED");

        tenantsName37.setFont(new java.awt.Font("Open Sans Medium", 1, 15)); // NOI18N
        tenantsName37.setText("(includes past balances)");

        javax.swing.GroupLayout PaymentRecordLayout = new javax.swing.GroupLayout(PaymentRecord);
        PaymentRecord.setLayout(PaymentRecordLayout);
        PaymentRecordLayout.setHorizontalGroup(
            PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentRecordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentRecordLayout.createSequentialGroup()
                        .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenantsName12)
                            .addComponent(tenantsName14)
                            .addComponent(tenantsName15)
                            .addComponent(tenantsName19)
                            .addComponent(tenantsName25)
                            .addComponent(tenantsName28)
                            .addComponent(tenantsName29)
                            .addComponent(tenantsName31)
                            .addComponent(tenantsName33)
                            .addComponent(tenantsName36))
                        .addGap(72, 72, 72)
                        .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenantsName18)
                            .addComponent(tenantsName17)
                            .addComponent(tenantsName16)
                            .addComponent(tenantsName26)
                            .addComponent(tenantsName27)
                            .addComponent(tenantsName30)
                            .addComponent(tenantsName32)
                            .addComponent(tenantsName34)
                            .addComponent(tenantsName35)))
                    .addGroup(PaymentRecordLayout.createSequentialGroup()
                        .addComponent(tenantsName20)
                        .addGap(28, 28, 28)
                        .addComponent(tenantsName21)
                        .addGap(18, 18, 18)
                        .addComponent(tenantsName22))
                    .addComponent(tenantsName37)))
        );
        PaymentRecordLayout.setVerticalGroup(
            PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentRecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tenantsName19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenantsName20)
                    .addComponent(tenantsName21)
                    .addComponent(tenantsName22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenantsName12)
                    .addComponent(tenantsName18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenantsName29)
                    .addComponent(tenantsName30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentRecordLayout.createSequentialGroup()
                        .addComponent(tenantsName14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantsName15))
                    .addGroup(PaymentRecordLayout.createSequentialGroup()
                        .addComponent(tenantsName17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantsName16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenantsName37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentRecordLayout.createSequentialGroup()
                        .addComponent(tenantsName31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantsName33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantsName36))
                    .addGroup(PaymentRecordLayout.createSequentialGroup()
                        .addComponent(tenantsName32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantsName34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantsName35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentRecordLayout.createSequentialGroup()
                        .addComponent(tenantsName25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantsName28))
                    .addGroup(PaymentRecordLayout.createSequentialGroup()
                        .addComponent(tenantsName26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantsName27))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(PaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaymentRecord;
    // End of variables declaration//GEN-END:variables
}
